#!/bin/bash
# ------------------------------------------------------------------------
# Bash script for reproducing file: hello.out
# Generated by: SciPipe 0.9.6
# SciPipe website: http://scipipe.org
# ------------------------------------------------------------------------

proc=$(printf '%-32s' "hello")
if [[ -f hello.out ]]; then
  echo "$(date '+%Y%m%d %H:%M:%S') | $proc | Some of these output files exist, so skipping: hello.out";
else
  echo "$(date '+%Y%m%d %H:%M:%S') | $proc | Executing: echo 'Hello ' > hello.out"
  echo 'Hello ' > hello.out
  echo "$(date '+%Y%m%d %H:%M:%S') | $proc |  Finished: echo 'Hello ' > hello.out"
fi;

